### PR TITLE
Remove tox.ini

### PR DESCRIPTION
**Pull request by zupo**
It hasn't been touched in a year and I doubt it still works.

### CODE REVIEW

**Comment by bertjwregeer** [comment]
I would recommend updating it instead, having a `tox.ini` is the way that I as a developer run tests for WebOb, Pyramid, Waitress and more. Feel free to steal from those. It is especially important for libraries we want people to consume, we want to test them across a wide range of python versions and platforms, and it is easy to plug tox into various build platform matrices.

**Comment by zupo** [comment]
@bertjwregeer: I'm not against it, but I can't seem to be able to learn to use tox and so I can't update it. I've tried several times, including a few months back when prepping pyramid_openapi3 for release. It just fails on my machine with strange errors. 

What I'm trying to say is: 1. it's not realistic for me to bring `tox.ini` to a workable state (and if it is workable, then it should be used in CI as well so it remains workable). -> it's better to remove it than to have a very outdated and broken `tox.ini`. If someone wants to tackle it, I'm all for it, but until then, it's probably best to remove it.

**Comment by stevepiercy** [comment]
Which parts from the makefile would you want to port to tox?

Do you want to test on 3.8 with an allowed failure, as well as must pass on 3.7?

Do you want to test on pypy3?

Do you want to use appveyor to test on Windows?

I know just enough to be dangerous, and I couldn't break tox more than it is borken now, so what the heck, why not take a stab at it?

**Comment by zupo** [comment]
> Which parts from the makefile would you want to port to tox?

Ideally, none. I'm really used to Makefiles. 

> Do you want to test on 3.8 with an allowed failure, as well as must pass on 3.7?

If we're testing, I'd say it needs to pass, no allowed failures.

> Do you want to test on pypy3?

Personally, no. Not against it if someone needs it.

> Do you want to use appveyor to test on Windows?

Personally, no. Not against it if someone needs it.

> I know just enough to be dangerous, and I couldn't break tox more than it is borken now, so what the heck, why not take a stab at it?

:)

**Comment by zupo** [comment]
@stevepiercy: any luck?

**Comment by stevepiercy** [comment]
Swamped through Friday.

**Comment by stevepiercy** [comment]
Let's close this PR and focus on a new minimal PR that now works.

**Pull request closed without merging**
