### PR TITLE
Add simple form-data support.

### PR DESCRIPTION
**Pull request by Wim-De-Clercq**
#122 

Maybe something is broken with CI because there was a broken test on master.

### CODE REVIEW

**Comment by zupo** [comment]
> Maybe something is broken with CI because there was a broken test on master.

Oh snap, you are right, it seems I've accidentally broken it here:

https://github.com/Pylons/pyramid_openapi3/commit/e074e443380b450a2d5a2654603bdfd835cec3d3#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47L70-L75

**Comment by zupo** [comment]
Hey @Wim-De-Clercq, I fixed master, can you please rebase this PR?

**Comment by zupo** [comment]
Ah, github allows me to rebase with one click, let's try it.

**Comment by zupo** [comment]
Hmm, three tests are failing on Python 3.9 on CI: https://app.circleci.com/pipelines/github/Pylons/pyramid_openapi3/423/workflows/fbb2f200-a157-4d17-8048-c9efdab30285/jobs/791

**Comment by zupo** [comment]
@Wim-De-Clercq: if I revert the commit from this PR, then all tests pass: https://github.com/Pylons/pyramid_openapi3/pull/135

Can you please check what could be the reason for tests failing on Python 3.9 after the commit from this PR is applied?

**Comment by zupo** [comment]
I did some reserach and PR #132 does not seem to be the culprit. More info: https://github.com/Pylons/pyramid_openapi3/issues/136

**Comment by Wim-De-Clercq** [comment]
@zupo 

The reason is actually a little bit complex and there are at least 2 issues which I found

**1)**  This test https://github.com/Pylons/pyramid_openapi3/blob/master/pyramid_openapi3/tests/test_app_construction.py#L145 can not work on its own. It needs the `app_config` instead of simple config. It can randomly fail when pytest decides to run this one before the other tests in the file.

-----

**2)** the use of the global `APIS` list causes issues in rare cases. Entirely depending on the order in which pytest runs the tests.
Sometimes the dummy api added by one of the view tests (for example here https://github.com/Pylons/pyramid_openapi3/blob/master/pyramid_openapi3/tests/test_views.py#L85)
Gets added before one of the tests adds the real `'pyramid_openapi3'` api to the `APIS` global.

If that happens, then some code does not run anymore because the `check_all_routes` will `return` early and not do the required actions for the `pyramid_openapi3` API.
(bottom part of the screenshot is the debugger where you can see the value of the `APIS`


And this causes a bunch of tests to fail.
Below is the content of a file with 1 test form the `test_views` combined with 1 test from `test_app_construction`. If you run this file, you'll have a 50/50 chance to reproduce it. The view test must run first make the other test fail.

To fix this, I think you may want a `autouse=True` fixture which does  `APIS.clear()`. Or perhaps consider doing a `continue` instead of a `return` when processing the `APIS`.

# A collapsible section with markdown
<details>
  <summary>Click to expand!</summary>
```python
"""Tests views."""

import tempfile
import typing as t

import pytest
from pyramid.config import Configurator
from pyramid.request import Request
from pyramid.testing import testConfig


class DummyStartResponse(object):
    def __call__(self, status, headerlist) -> None:
        """WSGI start_response protocol."""
        self.status = status
        self.headerlist = headerlist


MINIMAL_DOCUMENT = b"""
    openapi: "3.0.0"
    info:
      version: "1.0.0"
      title: Foo API
    paths:
      /foo:
        get:
          responses:
            200:
              description: A foo
"""

ALTERNATE_DOCUMENT = b"""
    openapi: "3.0.0"
    info:
      version: "1.0.0"
      title: Bar API
    paths:
      /bar:
        get:
          responses:
            200:
              description: A bar
"""

SPLIT_DOCUMENT = b"""
    openapi: "3.0.0"
    info:
      version: "1.0.0"
      title: Foo API
    paths:
      /foo:
        $ref: "paths.yaml#/foo"
"""

SPLIT_DOCUMENT_PATHS = b"""
    foo:
      get:
        responses:
          200:
            description: A foo
"""


def test_add_multiple_explorer_views() -> None:
    """Test registration of multiple viewa serving different Swagger UI."""
    with testConfig() as config:
        config.include("pyramid_openapi3")

        with tempfile.NamedTemporaryFile() as document:
            document.write(MINIMAL_DOCUMENT)
            document.seek(0)

            config.pyramid_openapi3_spec(
                document.name,
                route="/foo.yaml",
                route_name="foo_api_spec",
                apiname="foo_api",
            )


DOCUMENT = b"""
    openapi: "3.0.0"
    info:
      version: "1.0.0"
      title: Foo API
    servers:
      - url: /api/v1
    paths:
      /foo:
        get:
          responses:
            200:
              description: A foo
        post:
          responses:
            200:
              description: A POST foo
      /bar:
        get:
          responses:
            200:
              description: A bar
"""


@pytest.fixture
def document() -> t.Generator[t.IO, None, None]:
    """Load the DOCUMENT into a temp file."""
    with tempfile.NamedTemporaryFile() as document:
        document.write(DOCUMENT)
        document.seek(0)

        yield document


@pytest.fixture
def simple_config() -> Configurator:
    """Config fixture."""
    with testConfig() as config:
        config.include("pyramid_openapi3")

        yield config


@pytest.fixture
def app_config(
    simple_config: Configurator, document: t.IO
) -> t.Generator[Configurator, None, None]:
    """Incremented fixture that loads the DOCUMENT above into the config."""
    simple_config.pyramid_openapi3_spec(
        document.name, route="/foo.yaml", route_name="foo_api_spec"
    )
    yield simple_config


def foo_view(request: Request) -> str:
    """Return a dummy string."""
    return "Foo"  # pragma: no cover


def bar_view(request: Request) -> str:
    """Return a dummy string."""
    return "Bar"  # pragma: no cover


def test_routes_setting_generation(app_config: Configurator):
    """Test the `routes` setting is correctly created after app creation."""

    # Test that having multiple routes for a single route / pattern still works
    app_config.add_route(name="get_foo", pattern="/foo", request_method="GET")
    app_config.add_route(name="create_foo", pattern="/foo", request_method="POST")

    # Test the simple case of having no predicates on a route
    app_config.add_route(name="bar", pattern="/bar")

    # Add the views (needed for app creation)
    app_config.add_view(
        foo_view, route_name="get_foo", renderer="string", request_method="GET"
    )
    app_config.add_view(
        foo_view, route_name="create_foo", renderer="string", request_method="POST"
    )
    app_config.add_view(
        bar_view, route_name="bar", renderer="string", request_method="GET"
    )

    app_config.make_wsgi_app()

    settings = app_config.registry.settings["pyramid_openapi3"]
    # Assert that the `routes` setting object was created
    assert settings.get("routes") is not None
    # Assert that all 3 route names are in the `routes` setting
    # These should all map to `pyramid_openapi3` since that it the default apiname
    assert settings["routes"]["get_foo"] == "pyramid_openapi3"
    assert settings["routes"]["create_foo"] == "pyramid_openapi3"
    assert settings["routes"]["bar"] == "pyramid_openapi3"
```
</details>

**Pull request merged**
