### PR TITLE
Relax pyramid dependency version constraint

### PR DESCRIPTION
**Pull request by lkuchenb**
Enables Pyramid 2.x compatibility as discussed in #133

### CODE REVIEW

**Comment by lkuchenb** [comment]
@zupo Does this ring a bell?
```
==================================== ERRORS ====================================
_________ ERROR collecting pyramid_openapi3/tests/test_permissions.py __________
ImportError while importing test module '/home/circleci/repo/pyramid_openapi3/tests/test_permissions.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pyramid_openapi3/tests/test_permissions.py:10: in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
E   ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)
```

**Comment by zupo** [comment]
Looks like something related to https://docs.pylonsproject.org/projects/pyramid/en/latest/whatsnew-2.0.html. 

We might need to detect which version of pyramid is being used and change imports accordingly. Not sure if there is a better way to support 1.x and 2.x of Pyramid, maybe @stevepiercy has a better approach?

**Comment by stevepiercy** [comment]
From the Change History: https://docs.pylonsproject.org/projects/pyramid/en/latest/changes.html#backward-incompatibilities

- Removed pyramid.session.UnencryptedCookieSessionFactoryConfig. This session factory was replaced with pyramid.session.SignedCookieSessionFactory in Pyramid 1.5 and has been deprecated since then. See https://github.com/Pylons/pyramid/pull/3412
- Removed pyramid.session.signed_serialize, and pyramid.session.signed_deserialize. These methods were only used by the now-removed pyramid.session.UnencryptedCookieSessionFactoryConfig and were coupled to the vulnerable pickle serialization format which could lead to remove code execution if the secret key is compromised. See https://github.com/Pylons/pyramid/pull/3412

I would say that wherever you are using that method, you should replace it with something that is not deprecated since Pyramid 1.5. I don't think changing imports according to Pyramid version is the correct way forward.

**Comment by zupo** [comment]
Superseded by https://github.com/Pylons/pyramid_openapi3/pull/143 because I cannot push changes into @lkuchenb's fork.

**Pull request closed without merging**
